service: serverless-github-data

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 3002
  tableName: 'github-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
  customDomain:
    domainName: stats.openmined.org
    stage: prod
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  profile: openmined
  region: us-east-1
  environment:
    ACCESS_TOKEN: ${file(./env.yml):ACCESS_TOKEN}
    GITHUB_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["GithubDynamoDBTable", "Arn" ] }

functions:
  retrieveGithub:
    handler: index.retrieveGithub
    events:
      - http:
          path: retrieve
          method: get
          cors: true
  updateGithub:
    handler: index.updateGithub
    events:
      - schedule:
          name: update-github-cron
          description: 'Updates our DynamoDB table with the latest Github stats via a CRON job.'
          rate: rate(1 hour)

resources:
  Resources:
    GithubDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: dataId
            AttributeType: S
        KeySchema:
          -
            AttributeName: dataId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
